site_name: Biositing Tool Docs

site_description: Documentation for the Biositing Tool
copyright: Built by the Biositing Tool Development Team
site_url: https://biositing.jbei.org

repo_name: 'tylerhuntington/biositing-docs'
repo_url: 'https://github.com/tylerhuntington/biositing-docs'


nav:
  - Home: 'index.md'
#    # - Methodology:
#      - 'Property Prediction': 'methodology/property-prediction.md'
#      - 'Blend Tool': 'methodology/blend-tool.md'
  - User Reference:
      - 'REST API': 'user-guide/rest-api.md'
#  - Database Updates: 'database-updates.md'

theme:
  name: 'material'
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

plugins:
  - bibtex:
      bib_dir: "refs"
      cite_style: "pandoc"

extra_javascript:
  - static/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
